### ISSUE TITLE
How can I inverse segmaps without known camera pose

### ISSUE THREAD

**Issue by MrTornado24** [walnut-REE/sof#2]
Hi, thanks for your great work. I wonder if I have a real image, how can I inverse its free-viewed segmaps without known camera poses?

**Comment by fungtion** [comment]
@MrTornado24 Do you know how to perform inverse on FFHQ or CelebAMask-HQ, I can't find their camera parameters

**Comment by walnut-REE** [comment]
The most convenient way is to specify '--opt_cam' flag during training and automatically optimize for a plausible camera pose that agreed with our training dataset. For most cases, you can initialize with the default camera provided [here](https://github.com/walnut-REE/sof/blob/main/dataset/face_dataset.py#L536-L542), which is a front-facing camera in our training dataset.
