### ISSUE TITLE
Question about inverse rendering

### ISSUE THREAD

**Issue by arthur-qiu** [walnut-REE/sof#3]
Thanks for your impressive work. Does this repo provide the implementation of "back project in-the-wild portrait images into a latent vector in SOF geometric sampling space, and used for mutiview portrait generation"? Thanks.

**Comment by arthur-qiu** [comment]
Or I need to use GAN inversion to find the corresponding embeddings in the geometric sampling space and texture sampling space by optimization process?

**Comment by fungtion** [comment]
See last paragraph in "STEP 2 (optional): Inverse rendering"
