### ISSUE TITLE
What's the batch size?

### ISSUE THREAD

**Issue by fungtion** [walnut-REE/sof#5]
When I trained the network with multiview segmaps, only setting batch_size = 1 that the training can be performed, so is that means I have to set a 8x iteration value according to the yml file provided?
![individualImage](https://user-images.githubusercontent.com/10267392/156332209-2f8df98a-3bf9-487d-9b6e-b7ccebc001c2.png)

**Comment by walnut-REE** [comment]
Basically yes.
