### ISSUE TITLE
Is it normal not to reach reasonable results after long time of inversion?

### ISSUE THREAD

**Issue by RaymondJiangkw** [walnut-REE/sof#6]
Hi, I encounter a problem while performing single-view inversion as described in STEP 2 optional.

I use the `face_seg_single_view.yaml` and make the following changes: 
- I set `opt_cam` to be True, and initialize the camera to be frontal.
- I rename `batch_size_per_img_sidelength` to `batch_size` for correcting error.
- I rename `max_steps_per_img_sidelength` to `max_steps` for correcting error.
- I change value of `out_channels` from 19 to 20 to match the checkpoint.

However, after long time of training with inversion, this is what I get:
![image](https://user-images.githubusercontent.com/53508410/167662975-f25d8eb7-49f5-4fe3-83e4-3ff3b82e4ae7.png)

I am curious about whether this is a normal phenomenon? If not, is there some hint available?

Thanks a lot!

**Comment by RaymondJiangkw** [comment]
All right. I think I have solved the problem.

**Comment by fungtion** [comment]
@RaymondJiangkw Can you share your yaml file? I also cannot get a good inversion results.
